esphome:
  name: project-esp8266
  project:
    name: cblumer.project-esp8266
    version: 1.0.0

esp8266:
  board: esp01_1m
  restore_from_flash: true
  early_pin_init: false

packages:
  project-defaults: !include common/project-base.yaml