esphome:
  name: project-esp32
  project:
    name: cblumer.project-esp32
    version: 1.0.1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

packages:
  project-defaults: !include common/project-base.yaml

sensor:
- platform: internal_temperature
  name: "Internal Temperature"
  disabled_by_default: true
  entity_category: "diagnostic"