esphome:
  name: project-esp32
  project:
    name: cblumer.project-esp32
    version: 1.0.1

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  project-defaults: !include common/project-base.yaml

sensor:
- platform: internal_temperature
  name: "Internal Temperature"
  disabled_by_default: true
  entity_category: "diagnostic"