name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  base:
    uses: esphome/workflows/.github/workflows/publish.yml@dependabot/github_actions/esphome/build-action-3.1.0
    with:
      # CHANGEME: Set the filenames of your config files here:
      files: project-esp32.yaml,project-esp8266.yaml
      # CHANGEME: Set the name of your project here:
      name: Base ESPHome Project
  debug:
    uses: esphome/workflows/.github/workflows/publish.yml@dependabot/github_actions/esphome/build-action-3.1.0
    with:
      # CHANGEME: Set the filenames of your config files here:
      files: debug-esp32.yaml,debug-esp8266.yaml
      # CHANGEME: Set the name of your project here:
      name: Debug ESPHome Project